### ISSUE TITLE
Better config versioning management

### ISSUE THREAD

**Issue by balopat** [GoogleContainerTools/skaffold#2775]
Specs: https://docs.google.com/document/d/e/2PACX-1vRBN1vHjSGbs3ZmdvyzzhBn48NjeuP4OiTTG5mec_YrRzNDL63pFa1Xy1rgCUNiQXTjAE1QyvCr5yxX/pub

Based on the above, I have some recommendations around what to do with regards to version management, I believe these would simplify our lives: 

TODO: 
- [x] fail new_version script if current version is unreleased
- [x] we should mark a version released/unreleased, by a comment on top the config.go file maintained - explaining how to do config changes 
- [x] on every PR we should check for _structural changes_ in schemas. Fail if there is a structural change in a released version.
-  [x] in our release.sh script: if the latest version is unreleased, mark the latest version as released (in comment) 
- [ ] convert the above doc to a markdown / page on our skaffold.dev / DEVELOPMENT.md
