### ISSUE TITLE
[EPIC] Skaffold  docs

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#3023]
This issue is an EPIC for tracking all the docs work.

Docs:
-  #2465 - Skaffold diagnose docs ( Cancelled for this EPIC)
- [x] #1703  ( event api + control api)
  lets break it into 2 
   - [x] Event API docs ( in progress @tejal29)
   - [x] Trigger api docs
- [x] #3024 ( skaffold dev, run, debug docs)
- [x] Make "Insecure Registries title linkable" here https://skaffold.dev/docs/concepts/image_repositories/ so we can use it in the feature matrix.
- [x] Add docs for `skaffold init`. How to use and also fix #2951 
- [ ] Add docs on `skaffold version` command line
- [x] Add Feature matrix in deprecation policy docs [In progress] #3026
