### ISSUE TITLE
[Epic] Improve Skaffold's Logging and Output

### ISSUE THREAD

**Issue by nkubala** [GoogleContainerTools/skaffold#4517]
This is a top-level tracker for issues related to improving our surfaced logs and output.

- [x] Add configurable option to suppress logs - https://github.com/GoogleContainerTools/skaffold/issues/4512
- [x] Support suppressing build logs - https://github.com/GoogleContainerTools/skaffold/issues/4514
- [x] Support suppressing deploy logs - https://github.com/GoogleContainerTools/skaffold/issues/4515
- [x] Support suppressing status check output - https://github.com/GoogleContainerTools/skaffold/issues/4516
