### ISSUE TITLE
[Epic] Improve experience using skaffold init

### ISSUE THREAD

**Issue by MarlonGamez** [GoogleContainerTools/skaffold#4906]
This will serve as a top-level tracker for open issues related to skaffold init as of 2020/10/01

- [ ] #4417 - `init` should detect and configure Java multimodule projects for Buildpacks
- [X] #4335 - `skaffold init` should detect Polyglot Maven projects
- [x] #3814 - [FR] support setting artifact.context in skaffold init
- [ ] #3770 - skaffold init shows a list of warnings for templated image names.
- [x] #3766 - Skaffold init shouild generate a skaffold.yaml with default section.
- [ ] #3760 - skaffold init fails to identify proper workspace for artifact
- [x] #3678 - skaffold init shouldn't leave the user in an infinite loop of suggestions
- [x] #3661 - FR: Can `skaffold init --force` automatically select a builder if there are multiple builders and a single image detected?
- [ ] #2653 - `helm repo add` for skaffold init

**Comment by gsquared94** [comment]
<details>
  <summary>👍</summary>
making a comment to appease triage party</details>

**Comment by tejal29** [comment]
@marlon-gamez Should we close this or do we have plans to implement the remaining tasks?
