### ISSUE TITLE
Add support for implementing new test command

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5066]
This is a tracking issue for implementing new test command:

- [x] Make a util to hold the common cmd functionality (tracking issue - https://github.com/GoogleContainerTools/skaffold/issues/5116) (pr - https://github.com/GoogleContainerTools/skaffold/pull/5117)
- [x] Add a new test command and make it functional (tracking issue - https://github.com/GoogleContainerTools/skaffold/issues/5050) (pr - https://github.com/GoogleContainerTools/skaffold/pull/5118)
- [x] Split build and test into separate functions (tracking issue - https://github.com/GoogleContainerTools/skaffold/issues/5149)  (pr - https://github.com/GoogleContainerTools/skaffold/pull/5166)
- [x] Add test command to dev loop (tracking issue - https://github.com/GoogleContainerTools/skaffold/issues/5167) (pr - https://github.com/GoogleContainerTools/skaffold/pull/5166)
- [ ] Add an example for test command (tracking issue - https://github.com/GoogleContainerTools/skaffold/issues/5150)

Related: https://github.com/GoogleContainerTools/skaffold/issues/5116 https://github.com/GoogleContainerTools/skaffold/issues/5050, https://github.com/GoogleContainerTools/skaffold/issues/5051, https://github.com/GoogleContainerTools/skaffold/issues/5149, https://github.com/GoogleContainerTools/skaffold/issues/5150

**Comment by tejal29** [comment]
Thanks! Adding a comment to make triage party happy

**Comment by tejal29** [comment]
closing this as this now implemented.
