### ISSUE TITLE
Supporting custom tests in Skaffold

### ISSUE THREAD

**Issue by PriyaModali** [GoogleContainerTools/skaffold#5333]
This is a tracking issue for implementing new custom tester:
- [x] Supporting custom tests in Skaffold design doc (tracking issue - #5568)
- [x] Create a test factory to support multiple test types in Skaffold (tracking issue - #5379) (pr - #5378)
- [x] Design and implement custom tester functionality in skaffold (tracking issue - #5395) (pr - #5451)
- [x] Make necessary config changes to support the new custom tester in Skaffold (tracking issue - #5331) (pr - #5451)
- [x] Add a runnable example for CustomTest command (tracking issue -#5383) (pr - #5451)
- [x] Add distinct error codes for test failures (tracking issue - #5382)
       - [x] Structure test failures (tracking issue - #5384) (pr - #5385)
       - [x] Custom test failures (tracking issue - #5431) (pr - #5501)
 - [x] Add ability to re-execute tests  when test dependency changes (tracking issues - #5503, #5510) (pr - #5533)
       - [x] should not do a deploy
 - [x] Add events for `Test` phase (tracking issue - #5539, pr - #5573)
 - [x] Adding support for accessing built Images in custom test (tracking issue - #5534) (pr - #5535)
 - [x] Add documentation at docs/pipeline-stages/testers/ (tracking issue - #5520) (pr - #5521)

**Comment by nkubala** [comment]
commenting to make triage party happy
