### ISSUE TITLE
Implement API v2

### ISSUE THREAD

**Issue by MarlonGamez** [GoogleContainerTools/skaffold#5368]
### Tasks to complete for API v2
- [x] Create new proto definitions
- [x] Update server package to use newly defined service
- [x] Create functions to wrap/create these protos
- [x] Wire helper functions in to main skaffold code

**Comment by nkubala** [comment]
commenting to make triage party happy
