### ISSUE TITLE
[Epic] Skaffold Render v2

### ISSUE THREAD

**Issue by yuwenma** [GoogleContainerTools/skaffold#5673]
This is a tracking issue for skaffold v2 

 - [x] Legacy helm support: a user can continue to use `helm install` or `helm upgrade`
 - [ ] #7564
-  [x] Skaffold fix to translate v1 -> v2 configs
-  [x] Skaffold init support for v2 configs
-  [ ] Document new config schema and pipeline
-  [ ] #7565
-  [ ] #7566
-  [ ] Cloud Code Modules integration test - `skaffold debug` with modules makes all artifacts debuggable and port-forwarded

**Comment by tejal29** [comment]
Moving this to july end milestone since we need to finish it by then. 
Can you add individual tasks for this EPIC?

**Comment by tejal29** [comment]
Sync with @yuwenma to close this issue.

**Comment by aaron-prindle** [comment]
Closing this in favor of individual bugs created for each bullet that are currently in the `alpha-fixup2` milestone:
https://github.com/GoogleContainerTools/skaffold/milestone/45
