### ISSUE TITLE
Feature Request: add skaffold trace information (design + plumbing)

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#5756]
For getting more information about skaffold's performance and ensuring that skaffold does not have performance degradation over time, skaffold should adding trace information to skaffold commands.  Currently skaffold metrics can track the length of a `skaffold dev` session but there is no "child" trace information showing how specific actions took -  yaml parsing, builds, deploys, etc.

The steps that I have outlined for this work include:
- [x] update opentelemetry (`otel`) libs (v0.13.0 -> v0.20.0) for skaffold (to use updated APIs & trace implementation) - #5757
- [x] fully plumb trace exporters, etc. (similar to metric exporter) & plumb tracing through skaffold (usable by env var) - #5854 
- [x] add functionality/example where users can get generate & view their own trace information w/ jaeger - #5854

**Comment by MarlonGamez** [comment]
trying to make triage-party happy :)

**Comment by aaron-prindle** [comment]
Fixed with https://github.com/GoogleContainerTools/skaffold/pull/5854
