### ISSUE TITLE
[EPIC] Skaffold v3 config.

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#5857]
As we are working on v2 skaffold runner and v3 skaffold config, this is a place holder/ epic for all the work

For v3 config, 
- [X] send a survey out. #5556
- [x] define v3 config schema
- [x] run v3 config schema with v2 runner.

**Comment by yhrn** [comment]
Is there any more information/documentation on the progress of this? I was referred here from #2317.

**Comment by damlys** [comment]
I see this task is already closed, but cannot find a better place 😛 It seems that it's perfect time to implement #5856 and #2317. These improvements looks really useful. What do you think?
