### ISSUE TITLE
Remove need for Helm `artifactsOverride` by using Skaffold as a post-renderer

### ISSUE THREAD

**Issue by briandealwis** [GoogleContainerTools/skaffold#6706]
Helm 3.1 supports specifying a `post-renderer`, a simple filter that is afforded an opportunity to alter the rendered manifests prior to being applied to the cluster.  We use the post-renderer to support `skaffold debug` with Helm (#4732).  We should use the post-renderer as part of the `helm install` and `helm upgrade` to perform our manifest transformations more generally and thus side-step the need for `artifactsOverride` and our separate labelling step.  This change would greatly simplify configuration of Helm projects as well as avoiding resource churn (e.g., setting a label on a deployments will re-create its pods; #3133).

This change will require moving our minimum supported Helm version to 3.1.0.

- [x] Remove `artifactOverrides` and use Helm's post-renderer to call back into Skaffold to hydrate the Helm-rendered manifests (#6949)
- [x] Transition users using `artifactOverrides` (#6952)
- [ ] Add support for subsequently invoking user-configured post-renderers via `deploy.helm.flags` (#6951)

**Comment by tejal29** [comment]
@briandealwis are you planning to get this in ?

**Comment by briandealwis** [comment]
Yes.  Hit some stumbling blocks with testing.

**Comment by tejal29** [comment]
@briandealwis Is this done on v2?
