### ISSUE TITLE
v2 docs umbrella tracking issue

### ISSUE THREAD

**Issue by aaron-prindle** [GoogleContainerTools/skaffold#7375]
Putting all known todos for v2 docs into this tracking issue:
- [x] write Render page - (#7376 )
- [x] update all `Deployer` docs to `Renderer` docs - (#7376 )
- [x] properly setup v1 -> v2 links via https://www.docsy.dev/docs/adding-content/versioning/#adding-a-version-drop-down-menu
- [x] create a plan for when to make the v2 docs page the primary page
  - [x] see if we should disable robots from v1.skaffold.dev at that time so both don't show up in search results (or maybe we want that?)
  - [x] add a deprectation banner at that time to v1 docs https://www.docsy.dev/docs/adding-content/versioning/#adding-a-version-drop-down-menu
