### ISSUE TITLE
v2 - left over refactors. 

### ISSUE THREAD

**Issue by tejal29** [GoogleContainerTools/skaffold#7381]
This left over from #7326

- [x] Add Render in Runner.Deploy and Runner.DeployAndLog.  Render() to return a manifest list which can be piped to deployer. - #7329
- [x] Getting rid of  some complexity in `AddTagsToPodSelector` - #7329
- [ ] #7563
- [x] Getting rid of hydrationDir for kubectl render init
- [x] Fixing all existing deploy/kubectl_test.go to first render and then deploy for new style manifests. They are good tests for backward compatibility.  - #7329
    - [ ] Carry over reading remote manifests and manifests stored on GCS from deploy/kubectl to renderer/kubectl #7558 
- [ ] #7561
- [ ] #7562

**Comment by aaron-prindle** [comment]
Adding some notes from what I saw as well here:
- [ ] –output flag not working as intended, manifests always to to .kpt-pipeline/manifests.yaml
- [ ] –hydration dir doesn’t work as expected IIUC
  - [ ] –hydration-dir=manifests doesn’t output manifests/manifests.yaml, still .kpt-pipeline/manifests.yaml

**Comment by tejal29** [comment]
@marlon-gamez you are working on " Carry over reading remote manifests and manifests stored on GCS from deploy/kubectl to renderer/kubectl" right?

@gaghosh - Did you already work on getting rid of "Getting rid of hydrationDir for kubectl render function"
